## Environment
environment: production

url    : "//jonsuh.com"
url_protocol: "https:"
labs_url: "http://labs.jonsuh.com"
cdn_url: "https://s3.amazonaws.com/jonsuh.com"

paginate   : 10
limit_posts: 0
show_drafts: false
future     : false
unpublished: false